name = "RPGSimulator"
uuid = "940e48fe-9232-4331-8d03-3776d4f172d4"
version = "0.0.1"
authors = ["MaximusDiplodocus <desjobertmaxime1@gmail.com>"]

[deps]
BonitoBook = "b416d416-7a6e-4336-8c1a-1f8a8cd59518"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
BonitoBook = "0.2.0"
CSV = "0.10.15"
CairoMakie = "0.15.6"
Chain = "1.0.0"
DataFrames = "1.8.1"
Dates = "1.11.0"
Distributions = "0.25.122"
Observables = "0.5.5"
PlotlyJS = "0.18.17"
Plots = "1.41.1"
Random = "1.11.0"
StatsBase = "0.34.7"
Tables = "1.12.1"
WGLMakie = "0.13.6"
julia = "1.10"
