name = "RPGSimulator"
uuid = "940e48fe-9232-4331-8d03-3776d4f172d4"
version = "0.0.1"
authors = ["MaximusDiplodocus <desjobertmaxime1@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
CairoMakie = "0.15.6"
Chain = "1.0.0"
DataFrames = "1.8.1"
Dates = "1.11.0"
Distributions = "0.25.122"
Random = "1.11.0"
StatsBase = "0.34.7"
julia = "1.10"
